/*
  # Remove auth.users Foreign Key Constraint

  ## Overview
  Since we're implementing custom ZK authentication without Supabase Auth,
  we need to remove the foreign key constraint to auth.users and make profiles
  an independent table with self-managed UUIDs.

  ## Changes

  ### 1. Drop foreign key constraint
  Remove the REFERENCES constraint from profiles.id to auth.users(id)

  ### 2. Make id a standalone UUID field
  The id field will be a regular UUID primary key generated by the application
  or using gen_random_uuid()

  ## Important Notes
  - This is necessary because we're not using Supabase Auth (auth.users table)
  - Users are identified by their ZK public keys instead
  - The application layer manages user identity through ZK proofs
*/

-- First, we need to drop the foreign key constraint
-- The constraint name is automatically generated, so we need to find it first

DO $$
DECLARE
  constraint_name text;
BEGIN
  -- Find the foreign key constraint name
  SELECT tc.constraint_name INTO constraint_name
  FROM information_schema.table_constraints AS tc
  WHERE tc.table_name = 'profiles'
    AND tc.constraint_type = 'FOREIGN KEY'
    AND tc.constraint_name LIKE '%auth_users%';
  
  -- Drop the constraint if it exists
  IF constraint_name IS NOT NULL THEN
    EXECUTE 'ALTER TABLE profiles DROP CONSTRAINT ' || constraint_name;
  END IF;
END $$;

-- Now recreate the id column as a regular UUID primary key if needed
-- Since it already exists, we just need to ensure it has a default value

DO $$
BEGIN
  -- Check if id column has a default value, if not add one
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'profiles'
      AND column_name = 'id'
      AND column_default IS NOT NULL
  ) THEN
    ALTER TABLE profiles ALTER COLUMN id SET DEFAULT gen_random_uuid();
  END IF;
END $$;

-- Add a comment explaining the change
COMMENT ON COLUMN profiles.id IS 'UUID identifier managed by application. No longer references auth.users as we use custom ZK authentication.';